@extends('layouts.web')
@section('title','Subscription and profitability')
@section('content')
<style>.billing{padding:2rem 0 4rem}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:1rem}.metric{background:#fff;border:1px solid var(--line);border-radius:.9rem;padding:1rem}.metric strong{font-size:1.7rem;display:block}.plans{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem}.badge{display:inline-block;padding:.3rem .6rem;border-radius:99px;background:#fff3cd;color:#765b00}@media(max-width:800px){.grid,.plans{grid-template-columns:1fr}}</style>
<div class="wrap billing"><a href="{{ route('dashboard') }}">← Dashboard</a><div class="eyebrow">Demo billing · estimates</div><h1>Subscription and profitability</h1><p><span class="badge">Billing integration pending</span> All prices and margins are configurable demonstration assumptions, not audited financial information.</p>
<section class="grid"><div class="metric"><span>Current plan</span><strong>{{ $plan['name'] }}</strong></div><div class="metric"><span>Monthly revenue</span><strong>R{{ number_format($financials['revenue'],2) }}</strong></div><div class="metric"><span>Estimated variable cost</span><strong>R{{ number_format($financials['variable_cost'],2) }}</strong></div><div class="metric"><span>Contribution margin</span><strong>R{{ number_format($financials['margin'],2) }}</strong><small>{{ number_format($financials['margin_percent'],1) }}%</small></div></section>
<section><h2>Licence and usage</h2><div class="grid"><div class="metric"><span>Learners</span><strong>{{ $usage['learners'] }}/{{ $license?->max_learners ?? $plan['learners'] }}</strong></div><div class="metric"><span>Active staff</span><strong>{{ $usage['staff'] }}/{{ $plan['staff'] }}</strong></div><div class="metric"><span>AI markings this month</span><strong>{{ $usage['ai_requests'] }}/{{ $plan['ai_allowance'] }}</strong></div><div class="metric"><span>Estimated AI cost</span><strong>R{{ number_format($usage['ai_cost'],4) }}</strong></div></div></section>
<section><h2>Judge-friendly demo metrics</h2><div class="grid">@foreach($metrics as $label=>$value)<div class="metric"><span>{{ ucwords(str_replace('_',' ',$label)) }}</span><strong>{{ $value }}</strong><small>Seeded demonstration data</small></div>@endforeach</div></section>
<section><h2>Upgrade scenarios</h2><div class="plans">@foreach($plans as $candidate)<article class="panel"><h3>{{ $candidate['name'] }}</h3><strong>R{{ number_format($candidate['price']) }}/month</strong><p>{{ $candidate['learners'] }} learners · {{ $candidate['staff'] }} staff · {{ $candidate['ai_allowance'] }} AI markings</p></article>@endforeach</div></section>
<section class="panel"><h2>Assumptions</h2><p>Variable cost includes configured AI usage, notification cost, hosting allocation and support allocation. Taxes, payment-processing fees and add-ons are excluded.</p><p>Scenario: 10 Growth schools produces estimated MRR of R{{ number_format(10*config('hackathon.plans.growth.price'),2) }} before add-ons.</p></section></div>
@endsection
