@extends('assessments.layout')
@section('title','Review '.$quizAttempt->assessment->title)
@section('assessment-content')
@php($readOnly=$quizAttempt->status==='released' && !in_array('quiz_submissions.override_released',$permissions,true))
<div class="eyebrow">Teacher oversight</div><h1>Review: {{ $quizAttempt->assessment->title }}</h1><p>{{ $quizAttempt->learner->first_name }} {{ $quizAttempt->learner->last_name }} · {{ str_replace('_',' ',$quizAttempt->status) }}</p>
@if($readOnly)<p class="empty">This released result is read-only. Administrative override permission is required to change it.</p>@endif
<form method="POST" action="{{ route('quizzes.review.save',$quizAttempt->uuid) }}">@csrf
@foreach($quizAttempt->answers as $answer)<article class="panel" style="margin:1rem 0"><h2>{{ $answer->question->prompt }}</h2><p><strong>Learner answer:</strong> {{ $answer->selectedOption?->label ?? $answer->answer_text ?? 'No answer' }}</p><p><strong>Model answer:</strong> {{ $answer->question->model_answer ?: 'Not supplied' }}</p><p><strong>Rubric:</strong> {{ $answer->question->marking_guidance ?: 'Not supplied' }}</p>
@if($answer->ai_feedback)<p><strong>AI marks:</strong> {{ $answer->ai_suggested_mark }}/{{ $answer->marks_available }}</p><p><strong>AI feedback:</strong> {{ $answer->ai_feedback['grading_rationale'] }}</p><p><strong>Strengths:</strong> {{ implode('; ',$answer->ai_feedback['strengths']) ?: 'None identified' }}</p><p><strong>Improve:</strong> {{ implode('; ',$answer->ai_feedback['improvements']) ?: 'None identified' }}</p><p><strong>Misconceptions:</strong> {{ implode('; ',$answer->ai_feedback['misconceptions']) ?: 'None identified' }}</p><p><strong>Confidence:</strong> {{ number_format($answer->ai_feedback['confidence']*100) }}% · <strong>Requires review:</strong> {{ $answer->ai_feedback['requires_teacher_review'] ? 'Yes' : 'No' }}</p>@endif
@if(!$readOnly && !$answer->question->type->isObjective() && !$answer->ai_feedback)<button type="submit" formaction="{{ route('quizzes.answers.suggest',[$quizAttempt->uuid,$answer->uuid]) }}" formmethod="POST">AI Mark</button>@elseif(!$readOnly && !$answer->question->type->isObjective() && $answer->ai_feedback)<button type="submit" name="regenerate" value="1" formaction="{{ route('quizzes.answers.suggest',[$quizAttempt->uuid,$answer->uuid]) }}" formmethod="POST">Regenerate AI once</button>@endif
<label>Final mark (max {{ $answer->marks_available }})<input name="answers[{{ $answer->uuid }}][marks_awarded]" type="number" min="0" max="{{ $answer->marks_available }}" step=".01" value="{{ $answer->marks_awarded ?? $answer->ai_suggested_mark ?? 0 }}" @if($readOnly || $answer->question->type->isObjective())readonly @endif></label>
<label>Teacher feedback<textarea name="answers[{{ $answer->uuid }}][teacher_feedback]" @if($readOnly)readonly @endif>{{ $answer->teacher_feedback }}</textarea></label></article>@endforeach
@if(!$readOnly)<button type="submit" name="action" value="draft">Save Draft</button> <button type="submit" name="action" value="approve">Approve final marks</button>@endif</form>
<section class="panel" style="margin-top:1rem"><h2>Study plan and release</h2>
@if(!$quizAttempt->studyPlan && !$readOnly && $quizAttempt->status==='reviewed')<p>The first personalized plan will be generated through the AI Gateway when this result is released.</p>
@elseif($quizAttempt->studyPlan)<p><strong>Version {{ $quizAttempt->studyPlan->version }} · {{ $quizAttempt->studyPlan->status }}</strong> · {{ $quizAttempt->studyPlan->completion_percentage }}% complete · {{ $quizAttempt->studyPlan->time_spent_minutes }} minutes studied.</p><p>{{ $quizAttempt->studyPlan->content['summary'] }}</p>
@if(!$readOnly && $quizAttempt->studyPlan->status==='published')<form method="POST" action="{{ route('quizzes.study-plan.generate',$quizAttempt->uuid) }}">@csrf<input type="hidden" name="regenerate" value="1"><button>Regenerate as new version</button></form>@elseif(!$readOnly && $quizAttempt->studyPlan->status==='draft')<form method="POST" action="{{ route('quizzes.study-plan.approve',[$quizAttempt->uuid,$quizAttempt->studyPlan->uuid]) }}">@csrf<button>Publish updated plan</button></form>@endif
@endif
@if(!$readOnly && $quizAttempt->status==='reviewed')<form method="POST" action="{{ route('quizzes.release',$quizAttempt->uuid) }}" style="margin-top:1rem">@csrf<button>Release result to learner and parent</button></form>@endif</section>
@endsection
