@extends('learners.layout')
@section('title','Learner management')
@section('learner-content')
<h1>Learner management</h1><p>Search and manage learner profiles in the active organization. Archived learners are excluded by default.</p>
<form method="GET" action="{{ route('learners.index') }}" class="filters">
 <div class="wide"><label for="search">Search</label><input id="search" name="search" value="{{ request('search') }}" placeholder="Number or learner name"></div>
 <div><label for="learner_status">Learner status</label><select id="learner_status" name="learner_status"><option value="">All statuses</option>@foreach(Modules\Learners\Domain\Enums\LearnerStatus::cases() as $status)<option value="{{ $status->value }}" @selected(request('learner_status')===$status->value)>{{ ucfirst(str_replace('_',' ',$status->value)) }}</option>@endforeach</select></div>
 <div><label for="onboarding_status">Onboarding</label><select id="onboarding_status" name="onboarding_status"><option value="">All</option>@foreach(['pending','in_progress','completed'] as $value)<option value="{{ $value }}" @selected(request('onboarding_status')===$value)>{{ ucfirst(str_replace('_',' ',$value)) }}</option>@endforeach</select></div>
 @foreach([['academic_year_id','Academic year',$academicYears],['curriculum_id','Curriculum',$curricula],['grade_id','Grade',$grades],['class_id','Class',$classes]] as [$name,$label,$options])<div><label for="{{ $name }}">{{ $label }}</label><select id="{{ $name }}" name="{{ $name }}"><option value="">All</option>@foreach($options as $option)<option value="{{ $option->id }}" @selected(request($name)===$option->id)>{{ $option->name }}</option>@endforeach</select></div>@endforeach
 <div><label for="portal_access_enabled">Portal access</label><select id="portal_access_enabled" name="portal_access_enabled"><option value="">Any</option><option value="1" @selected(request('portal_access_enabled')==='1')>Enabled</option><option value="0" @selected(request('portal_access_enabled')==='0')>Disabled</option></select></div>
 <div><label for="archived">Archive</label><select id="archived" name="archived"><option value="">Exclude archived</option><option value="1" @selected(request('archived')==='1')>Archived only</option><option value="0" @selected(request('archived')==='0')>Not archived</option></select></div>
 <div><label for="admission_date_from">Admitted from</label><input id="admission_date_from" type="date" name="admission_date_from" value="{{ request('admission_date_from') }}"></div><div><label for="admission_date_to">Admitted to</label><input id="admission_date_to" type="date" name="admission_date_to" value="{{ request('admission_date_to') }}"></div>
 <div><label for="sort">Sort by</label><select id="sort" name="sort">@foreach(['learner_number','first_name','last_name','admission_date','learner_status','created_date'] as $value)<option value="{{ $value }}" @selected(request('sort','learner_number')===$value)>{{ ucfirst(str_replace('_',' ',$value)) }}</option>@endforeach</select></div><div><label for="direction">Direction</label><select id="direction" name="direction"><option value="asc">Ascending</option><option value="desc" @selected(request('direction')==='desc')>Descending</option></select></div>
 <div class="wide actions-inline"><button type="submit">Apply filters</button><a class="button secondary" href="{{ route('learners.index') }}">Clear</a></div>
</form>
@if($learners->isEmpty())<div class="empty">@if(!$hasAnyLearners)No learners have been added to this organization.@elseif($filtersApplied)No learners match the current search and filters.@elseNo active learner profiles are available. Archived records are excluded by default.@endif</div>@else
<p class="meta">Showing {{ $learners->firstItem() }}–{{ $learners->lastItem() }} of {{ $learners->total() }} learners.</p><div class="table-wrap"><table class="learner-table"><thead><tr><th>Learner number</th><th>Admission number</th><th>Full name</th><th>Grade</th><th>Class</th><th>Status</th><th>Onboarding</th><th>Portal</th><th>Admission date</th><th>Actions</th></tr></thead><tbody>@foreach($learners as $learner)<tr><td>{{ $learner->learner_number }}</td><td>{{ $learner->admission_number ?: '—' }}</td><td>{{ trim($learner->first_name.' '.$learner->middle_name.' '.$learner->last_name) }}</td><td>{{ $learner->currentGrade?->name ?? 'Not assigned' }}</td><td>{{ $learner->currentClass?->name ?? 'Not assigned' }}</td><td><span class="badge">{{ str_replace('_',' ',$learner->learner_status->value) }}</span></td><td>{{ str_replace('_',' ',$learner->onboarding_status) }}</td><td>{{ $learner->portal_access_enabled ? 'Enabled' : 'Disabled' }}</td><td>{{ $learner->admission_date?->toDateString() ?? '—' }}</td><td><div class="actions-inline"><a href="{{ route('learners.show',$learner->uuid) }}">View</a>@if(in_array('learners.update',$permissions,true) && $learner->learner_status->value!=='archived')<a href="{{ route('learners.edit',$learner->uuid) }}">Edit</a>@endif</div></td></tr>@endforeach</tbody></table></div>
<nav class="pagination" aria-label="Learner pages">@if($learners->previousPageUrl())<a href="{{ $learners->previousPageUrl() }}">Previous</a>@endif @foreach(range(1,$learners->lastPage()) as $page)@if($page===$learners->currentPage())<span class="current" aria-current="page">{{ $page }}</span>@elseif(abs($page-$learners->currentPage())<=2)<a href="{{ $learners->url($page) }}">{{ $page }}</a>@endif @endforeach @if($learners->nextPageUrl())<a href="{{ $learners->nextPageUrl() }}">Next</a>@endif <span>Page {{ $learners->currentPage() }} of {{ $learners->lastPage() }}</span></nav>@endif
@endsection
