@extends('layouts.web')
@section('content')
<style>
.learner-shell{padding:2rem 0 4rem}.learner-nav,.learner-heading{display:flex;align-items:center;justify-content:space-between;gap:1rem;margin-bottom:1.25rem}.learner-nav .links,.actions-inline{display:flex;gap:.6rem;align-items:center;flex-wrap:wrap}.learner-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:1rem}.learner-table{width:100%;border-collapse:collapse;background:var(--card);border:1px solid var(--line)}.learner-table th,.learner-table td{padding:.7rem;text-align:left;border-bottom:1px solid var(--line);vertical-align:top;white-space:nowrap}.learner-table th{font-size:.76rem;text-transform:uppercase;color:var(--muted)}.table-wrap{overflow-x:auto;border-radius:.8rem}.filters{display:grid;grid-template-columns:repeat(4,1fr);gap:.7rem;margin:1rem 0}.filters .wide{grid-column:span 2}.filters input,.filters select,.learner-form input,.learner-form select,.learner-form textarea{width:100%;padding:.7rem;border:1px solid #b9c5d3;border-radius:.55rem;background:var(--card);color:var(--ink);font:inherit}.learner-form{display:grid;grid-template-columns:repeat(2,1fr);gap:1rem}.learner-form fieldset{grid-column:1/-1;border:1px solid var(--line);border-radius:.8rem;padding:1rem;display:grid;grid-template-columns:repeat(2,1fr);gap:1rem}.learner-form legend{font-weight:800;padding:0 .35rem}.learner-form .wide{grid-column:1/-1}.learner-form label{display:block;font-weight:700;margin-bottom:.3rem}.field-error{display:block;color:var(--danger);font-size:.88rem}.status-message{padding:.8rem;border-radius:.6rem;background:#e7f8f3;color:#08765f}.pagination{display:flex;gap:.45rem;margin-top:1rem;align-items:center;flex-wrap:wrap}.pagination a,.pagination span{padding:.4rem .65rem;border:1px solid var(--line);border-radius:.4rem}.pagination .current{background:var(--primary);color:white}.detail-list{display:grid;grid-template-columns:repeat(2,1fr);gap:.25rem}.detail-list div{padding:.65rem;border-bottom:1px solid var(--line)}.detail-list dt{font-size:.8rem;color:var(--muted)}.detail-list dd{margin:.2rem 0 0}.badge{display:inline-block;padding:.2rem .5rem;border-radius:999px;background:#edf3fb;font-size:.82rem}.danger{background:var(--danger)}.empty{padding:2rem;text-align:center;background:var(--card);border:1px dashed var(--line);border-radius:.8rem}.help{font-size:.88rem;color:var(--muted)}.history{padding-left:1.2rem}.history li{margin-bottom:.8rem}@media(max-width:850px){.filters{grid-template-columns:repeat(2,1fr)}.learner-grid{grid-template-columns:1fr}}@media(max-width:600px){.filters,.learner-form,.learner-form fieldset,.detail-list{grid-template-columns:1fr}.filters .wide,.learner-form .wide{grid-column:auto}.learner-nav,.learner-heading{align-items:flex-start;flex-direction:column}}
</style>
<div class="wrap learner-shell">
 <nav class="learner-nav" aria-label="Learner management"><div><div class="eyebrow">{{ $organization->name }}</div><a href="{{ route('dashboard') }}">Dashboard</a> / <a href="{{ route('learners.index') }}">Learners</a></div><div class="links">@if(in_array('learners.create',$permissions,true))<a class="button" href="{{ route('learners.create') }}">Add learner</a>@endif</div></nav>
 @if(session('status'))<p class="status-message" role="status">{{ session('status') }}</p>@endif
 @if($errors->any())<div class="errors" role="alert"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
 @yield('learner-content')
</div>
@endsection
