@extends('learners.layout')
@section('title','Learner profile')
@section('learner-content')
<div class="learner-heading"><div><div class="eyebrow">Learner profile</div><h1>{{ trim($learner->first_name.' '.$learner->middle_name.' '.$learner->last_name) }}</h1><p>{{ $learner->learner_number }}</p></div><div class="actions-inline">@if(in_array('attendance.view',$permissions,true))<a class="button secondary" href="{{ route('learners.attendance',$learner->uuid) }}">Attendance history</a>@endif @if(in_array('assessments.view',$permissions,true))<a class="button secondary" href="{{ route('learners.results',$learner->uuid) }}">Assessment results</a>@endif @if(in_array('learners.update',$permissions,true) && $learner->learner_status->value!=='archived')<a class="button secondary" href="{{ route('learners.edit',$learner->uuid) }}">Edit profile</a>@endif @if(in_array('learners.manage_academic_profile',$permissions,true) && $learner->learner_status->value!=='archived')<a class="button secondary" href="{{ route('learners.academic-placement.edit',$learner->uuid) }}">Update placement</a>@endif</div></div>
<div class="learner-grid"><section class="panel"><h2>Identity and contact</h2><dl class="detail-list">@foreach([['Learner number',$learner->learner_number],['Admission number',$learner->admission_number],['Full name',trim($learner->first_name.' '.$learner->middle_name.' '.$learner->last_name)],['Preferred name',$learner->preferred_name],['Date of birth',$learner->date_of_birth?->toDateString()],['Email',$learner->learner_email],['Phone',$learner->learner_phone],['Address',$learner->residential_address],['City',$learner->city],['Province',$learner->province],['Country',$learner->country],['Postal code',$learner->postal_code]] as [$label,$content])<div><dt>{{ $label }}</dt><dd>{{ $content ?: 'Not provided' }}</dd></div>@endforeach</dl></section>
<section class="panel"><h2>Academic placement</h2><dl class="detail-list">@foreach([['Academic year',$learner->currentAcademicYear?->name],['Curriculum',$learner->curriculum?->name],['Grade',$learner->currentGrade?->name],['Class',$learner->currentClass?->name],['Admission date',$learner->admission_date?->toDateString()],['Expected completion',$learner->expected_completion_date?->toDateString()],['Previous institution',$learner->previous_institution],['Language of instruction',$learner->language_of_instruction],['Home language',$learner->home_language],['Learning mode',$learner->learning_mode]] as [$label,$content])<div><dt>{{ $label }}</dt><dd>{{ $content ?: 'Not assigned' }}</dd></div>@endforeach</dl></section></div>
<section class="panel" style="margin-top:1rem"><h2>Operational state</h2><dl class="detail-list"><div><dt>Learner status</dt><dd><span class="badge">{{ ucfirst(str_replace('_',' ',$learner->learner_status->value)) }}</span></dd></div><div><dt>Onboarding status</dt><dd>{{ ucfirst(str_replace('_',' ',$learner->onboarding_status)) }}</dd></div><div><dt>Portal access</dt><dd>{{ $learner->portal_access_enabled ? 'Enabled' : 'Disabled' }}</dd></div><div><dt>Account state</dt><dd>{{ $learner->user_id ? 'Linked account' : 'Profile only' }}</dd></div><div><dt>Archived</dt><dd>{{ $learner->archived_at ? $learner->archived_at->toDayDateTimeString() : 'No' }}</dd></div><div><dt>Created</dt><dd>{{ $learner->created_at->toDayDateTimeString() }}</dd></div><div><dt>Updated</dt><dd>{{ $learner->updated_at->toDayDateTimeString() }}</dd></div></dl></section>
@if(in_array('learners.manage_status',$permissions,true) && $learner->learner_status->value!=='archived' && count($transitions)>0)<section class="panel" style="margin-top:1rem"><h2>Change status</h2><p>Current status: <strong>{{ str_replace('_',' ',$learner->learner_status->value) }}</strong></p><form method="POST" action="{{ route('learners.status',$learner->uuid) }}" class="learner-form" onsubmit="return confirm('Confirm this learner status change?')">@csrf<div><label for="status">New status</label><select id="status" name="status" required>@foreach($transitions as $transition)<option value="{{ $transition->value }}">{{ ucfirst(str_replace('_',' ',$transition->value)) }}</option>@endforeach</select></div><div><label for="status_reason">Reason (optional)</label><input id="status_reason" name="reason" maxlength="2000"></div><div class="wide"><button type="submit">Change status</button></div></form></section>@endif
<section class="panel" style="margin-top:1rem"><h2>Archive controls</h2>@if($learner->learner_status->value==='archived' && in_array('learners.restore',$permissions,true))<form method="POST" action="{{ route('learners.restore',$learner->uuid) }}" class="learner-form" onsubmit="return confirm('Restore this learner to their previous status?')">@csrf<div><label for="restore_reason">Reason (optional)</label><input id="restore_reason" name="reason" maxlength="2000"></div><div><button type="submit">Restore learner</button></div></form>@elseif($learner->learner_status->value!=='archived' && in_array('learners.archive',$permissions,true))<form method="POST" action="{{ route('learners.archive',$learner->uuid) }}" class="learner-form" onsubmit="return confirm('Archive this learner?')">@csrf<div><label for="archive_reason">Reason (optional)</label><input id="archive_reason" name="reason" maxlength="2000"></div><div><button class="danger" type="submit">Archive learner</button></div></form>@else<p>No archive action is available.</p>@endif</section>
@if(in_array('learners.view_status_history',$permissions,true))<section class="panel" style="margin-top:1rem"><h2>Status history</h2>@if($history->isEmpty())<p class="empty">No status changes have been recorded.</p>@else<ol class="history">@foreach($history as $entry)<li><strong>{{ ucfirst(str_replace('_',' ',$entry->previous_status->value)) }} → {{ ucfirst(str_replace('_',' ',$entry->new_status->value)) }}</strong><br>{{ $entry->reason ?: 'No reason provided.' }}<br><span class="meta">{{ $entry->actor?->name ?? 'System' }} · {{ $entry->changed_at->toDayDateTimeString() }}</span></li>@endforeach</ol>@endif</section>@endif
<p><a href="{{ route('learners.index') }}">← Back to learner directory</a></p>
@endsection
