@extends('layouts.web')
@section('content')
<style>
.staff-shell{padding:2rem 0 4rem}.staff-nav{display:flex;align-items:center;justify-content:space-between;gap:1rem;margin-bottom:1.5rem}.staff-nav .links{display:flex;gap:.75rem;align-items:center;flex-wrap:wrap}.staff-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:1rem}.staff-table{width:100%;border-collapse:collapse;background:var(--card);border:1px solid var(--line)}.staff-table th,.staff-table td{padding:.75rem;text-align:left;border-bottom:1px solid var(--line);vertical-align:top}.staff-table th{font-size:.78rem;text-transform:uppercase;color:var(--muted)}.table-wrap{overflow-x:auto;border-radius:.8rem}.filters{display:grid;grid-template-columns:2fr repeat(4,1fr);gap:.75rem;margin:1rem 0}.filters input,.filters select,.staff-form input,.staff-form select,.staff-form textarea{width:100%;padding:.7rem;border:1px solid #b9c5d3;border-radius:.55rem;background:var(--card);color:var(--ink);font:inherit}.staff-form{display:grid;grid-template-columns:repeat(2,1fr);gap:1rem}.staff-form .wide{grid-column:1/-1}.staff-form label{display:block;font-weight:700;margin-bottom:.3rem}.status-message{padding:.8rem;border-radius:.6rem;background:#e7f8f3;color:#08765f}.pagination{display:flex;gap:.5rem;margin-top:1rem;align-items:center}.pagination a{padding:.45rem .7rem;border:1px solid var(--line);border-radius:.4rem}.detail-list{display:grid;grid-template-columns:repeat(2,1fr);gap:.8rem}.detail-list div{padding:.8rem;border-bottom:1px solid var(--line)}.detail-list dt{font-size:.8rem;color:var(--muted)}.detail-list dd{margin:.2rem 0 0}.danger{background:#b42318}.actions-inline{display:flex;gap:.5rem;flex-wrap:wrap}.actions-inline form{margin:0}@media(max-width:900px){.filters{grid-template-columns:1fr 1fr}.staff-grid{grid-template-columns:1fr}}@media(max-width:600px){.filters,.staff-form,.detail-list{grid-template-columns:1fr}.staff-form .wide{grid-column:auto}.staff-nav{align-items:flex-start;flex-direction:column}}
</style>
<div class="wrap staff-shell">
    <nav class="staff-nav" aria-label="Staff management"><div><div class="eyebrow">{{ $organization->name }}</div><a href="{{ route('dashboard') }}">Dashboard</a> / <a href="{{ route('staff.index') }}">Staff</a></div><div class="links">@if(in_array('staff.create', $permissions, true))<a class="button" href="{{ route('staff.create') }}">Add staff</a>@endif</div></nav>
    @if(session('status'))<p class="status-message">{{ session('status') }}</p>@endif
    @yield('staff-content')
</div>
@endsection
