@extends('reports.layout')
@section('title','Report card')
@section('reports-content')
<h1>{{$reportCard->learner->first_name}} {{$reportCard->learner->last_name}}</h1>
<p>{{$reportCard->period->name}} · {{$reportCard->grade->name}} · {{$reportCard->classGroup->name}} · Version {{$reportCard->version_number}} · <span class="pill">{{$reportCard->status->value}}</span></p>
<div class="actions"><a class="button secondary" href="{{route('reports.pdf',$reportCard->uuid)}}">Export PDF</a>@if(in_array('reports.update',$permissions,true) && in_array($reportCard->status->value,['draft','generated']))<form method="POST" action="{{route('reports.regenerate',$reportCard->uuid)}}">@csrf<button>Regenerate draft</button></form>@endif</div>
<table class="table"><tr><th>Subject</th><th>Marked</th><th>Weight</th><th>Result</th><th>Grade</th></tr>@foreach($reportCard->subjects as $s)<tr><td>{{$s->subject_name_snapshot}} {{$s->subject_code_snapshot}}</td><td>{{$s->marked_assessment_count}}</td><td>{{$s->total_valid_weighting ?? 'Unweighted'}}</td><td>{{$s->calculated_percentage === null?str_replace('_',' ',$s->subject_result_status->value):$s->calculated_percentage.'%'}}</td><td>{{$s->grading_band_label}} {{$s->grading_band_symbol}}</td></tr>@endforeach</table>
<div class="grid"><div class="panel"><h3>Overall average</h3><strong>{{$reportCard->overall_average === null?'Not calculated':$reportCard->overall_average.'%'}}</strong></div>@if($reportCard->template->show_attendance)<div class="panel"><h3>Recorded finalized attendance</h3><p>{{$reportCard->attendance_session_count}} sessions · Present {{$reportCard->present_count}} · Absent {{$reportCard->absent_count}} · Late {{$reportCard->late_count}} · Excused {{$reportCard->excused_count}} · Remote {{$reportCard->remote_count}}</p></div>@endif</div>
@if($reportCard->template->show_overall_comment)<div class="panel"><h3>Overall comment</h3><p>{{$reportCard->overall_comment ?? 'No comment recorded.'}}</p></div>@endif
@if(in_array('reports.manage_comments',$permissions,true) && !in_array($reportCard->status->value,['published','withdrawn']))<form class="panel" method="POST" action="{{route('reports.comments',$reportCard->uuid)}}">@csrf<div class="field"><label>Overall comment<textarea name="overall_comment" maxlength="4000">{{$reportCard->overall_comment}}</textarea></label></div><div class="field"><label>Additional comment type<select name="comment_type"><option value="general">General</option><option value="class_teacher">Class teacher</option><option value="academic_admin">Academic administrator</option><option value="principal">Principal</option></select></label></div><div class="field"><label>Plain-text comment<textarea name="comment" maxlength="4000"></textarea></label></div><button>Save comments</button></form>@endif
<div class="actions">@foreach(['review','approve','publish'] as $a)@if(in_array('reports.'.$a,$permissions,true))<form method="POST" action="{{route('reports.'.$a,$reportCard->uuid)}}">@csrf<button>{{$a}}</button></form>@endif @endforeach @if(in_array('reports.withdraw',$permissions,true) && $reportCard->status->value==='published')<form method="POST" action="{{route('reports.withdraw',$reportCard->uuid)}}">@csrf<input name="reason" required maxlength="2000" placeholder="Withdrawal reason"><button class="danger">Withdraw</button></form>@endif</div>
<h2>Version history</h2><ul>@foreach($history as $h)<li><a href="{{route('reports.show',$h->uuid)}}">Version {{$h->version_number}}</a> · {{$h->status->value}} · {{$h->generated_at?->toDateTimeString()}}</li>@endforeach</ul>
@endsection
