@extends('learners.layout')
@section('title','Guardian profile')
@section('learner-content')
<div class="learner-heading"><div><div class="eyebrow">Guardian profile</div><h1>{{ $guardian->first_name }} {{ $guardian->last_name }}</h1><p>{{ ucfirst($guardian->status->value) }}</p></div><div class="actions-inline">@if(in_array('guardians.update',$permissions,true)&&$guardian->status->value!=='archived')<a class="button secondary" href="{{ route('guardians.edit',$guardian->uuid) }}">Edit</a>@endif</div></div>
<section class="panel"><h2>Contact and access</h2><dl class="detail-list">@foreach([['Email',$guardian->email],['Phone',$guardian->phone],['Preferred channel',ucfirst($guardian->preferred_communication_channel)],['Address',$guardian->address],['Portal identity',$guardian->user_id ? 'Linked through organization membership' : 'Profile only — no login access'],['Invitation state',$guardian->organizationMembership?->status?->value]] as [$label,$value])<div><dt>{{ $label }}</dt><dd>{{ $value ?: 'Not provided' }}</dd></div>@endforeach</dl></section>
<section class="panel" style="margin-top:1rem"><h2>Linked learners</h2>@if($guardian->relationships->isEmpty())<p class="empty">This guardian is not linked to a learner.</p>@else<ul>@foreach($guardian->relationships as $relationship)<li><a href="{{ route('learners.show',$relationship->learner->uuid) }}">{{ $relationship->learner->first_name }} {{ $relationship->learner->last_name }}</a> — {{ str_replace('_',' ',$relationship->relationship_type) }}@if($relationship->is_primary), primary contact @endif</li>@endforeach</ul>@endif</section>
@if(in_array('guardians.archive',$permissions,true)&&$guardian->status->value!=='archived')<section class="panel" style="margin-top:1rem"><h2>Archive</h2><form method="POST" action="{{ route('guardians.archive',$guardian->uuid) }}" onsubmit="return confirm('Archive this guardian and deactivate their learner links?')">@csrf<button class="danger">Archive guardian</button></form></section>@endif
<p><a href="{{ route('guardians.index') }}">← Guardian directory</a></p>
@endsection
