@extends('attendance.layout')
@section('title','Attendance')
@section('attendance-content')
<h1>Attendance management</h1><p class="muted">Totals below use recorded finalized sessions only. No attendance percentage is inferred from incomplete coverage.</p>
<div class="grid"><div class="card"><strong>{{ $todayCount }}</strong><br>Today's sessions</div>@foreach(['draft','open','finalized'] as $status)<div class="card"><strong>{{ $counts[$status] ?? 0 }}</strong><br>{{ ucfirst($status) }}</div>@endforeach</div>
<div class="grid" style="margin-top:1rem">@foreach(['present','absent','late','excused','remote'] as $status)<div class="card"><strong>{{ $totals[$status] ?? 0 }}</strong><br>{{ ucfirst($status) }}</div>@endforeach</div>
<form class="filters" method="get"><input type="date" name="date_from" value="{{ request('date_from') }}"><input type="date" name="date_to" value="{{ request('date_to') }}"><select name="academic_year_id"><option value="">All years</option>@foreach($years as $x)<option value="{{ $x->id }}" @selected(request('academic_year_id')===$x->id)>{{ $x->name }}</option>@endforeach</select><select name="academic_term_id"><option value="">All terms</option>@foreach($terms as $x)<option value="{{ $x->id }}">{{ $x->name }}</option>@endforeach</select><select name="class_id"><option value="">All classes</option>@foreach($classes as $x)<option value="{{ $x->id }}">{{ $x->name }}</option>@endforeach</select><select name="subject_id"><option value="">All subjects</option>@foreach($subjects as $x)<option value="{{ $x->id }}">{{ $x->name }}</option>@endforeach</select><select name="staff_profile_id"><option value="">All staff</option>@foreach($staff as $x)<option value="{{ $x->id }}">{{ $x->first_name }} {{ $x->last_name }}</option>@endforeach</select><select name="status"><option value="">All statuses</option>@foreach($sessionStatuses as $x)<option value="{{ $x->value }}">{{ ucfirst($x->value) }}</option>@endforeach</select><select name="session_type"><option value="">All types</option>@foreach($sessionTypes as $x)<option value="{{ $x->value }}">{{ ucfirst($x->value) }}</option>@endforeach</select><button>Filter</button></form>
<div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Class / subject</th><th>Type</th><th>Staff</th><th>Status</th><th>Recorded</th><th>Action</th></tr></thead><tbody>@forelse($sessions as $session)<tr><td>{{ $session->session_date->format('Y-m-d') }}</td><td>{{ $session->classGroup->name }}<br><span class="muted">{{ $session->subject?->name ?? 'No subject' }}</span></td><td>{{ ucfirst($session->session_type->value) }}</td><td>{{ $session->staffProfile ? $session->staffProfile->first_name.' '.$session->staffProfile->last_name : '—' }}</td><td><span class="badge">{{ $session->status->value }}</span></td><td>{{ $session->recorded_count }}/{{ $session->entries_count }}</td><td><a href="{{ route('attendance.register',$session->uuid) }}">Open register</a></td></tr>@empty<tr><td colspan="7">No matching sessions.</td></tr>@endforelse</tbody></table></div>{{ $sessions->links() }}
@endsection
