@extends('attendance.layout')
@section('title','Attendance register')
@section('attendance-content')
<div class="bar"><div><h1>{{ $session->title ?: $session->classGroup->name.' register' }}</h1><p>{{ $session->session_date->format('Y-m-d') }} · {{ $session->subject?->name ?? ucfirst($session->session_type->value) }} · <span class="badge">{{ $session->status->value }}</span></p></div>@if(in_array('attendance.export',$permissions,true))<a href="{{ route('attendance.export',$session->uuid) }}">Export safe CSV</a>@endif</div>
@if($session->status->value === 'finalized')<p class="notice">This finalized register is locked and read-only.</p>@endif
<form method="post" action="{{ route('attendance.register.store',$session->uuid) }}">@csrf<div class="actions"><button type="button" id="mark-all">Mark all present (unsaved)</button><span class="muted">You must submit to save changes.</span></div><div class="table-wrap"><table class="table register"><thead><tr><th>Learner</th><th>Class</th><th>Status</th><th>Arrival</th><th>Reason</th><th>Safe note</th></tr></thead><tbody>@foreach($session->entries as $i=>$entry)<tr><td>{{ $entry->learner->learner_number }}<br>{{ $entry->learner->first_name }} {{ $entry->learner->last_name }}<input type="hidden" name="entries[{{ $i }}][entry_uuid]" value="{{ $entry->uuid }}"></td><td>{{ $entry->learner->currentClass?->name }}</td><td><select class="attendance-status" name="entries[{{ $i }}][status]" @disabled($session->status->value === 'finalized')>@foreach($statuses as $status)<option value="{{ $status->value }}" @selected($entry->status===$status)>{{ ucfirst(str_replace('_',' ',$status->value)) }}</option>@endforeach</select></td><td><input type="time" name="entries[{{ $i }}][arrival_time]" value="{{ $entry->arrival_time }}" @disabled($session->status->value === 'finalized')></td><td><input name="entries[{{ $i }}][reason]" maxlength="500" value="{{ $entry->reason }}" @disabled($session->status->value === 'finalized')></td><td><input name="entries[{{ $i }}][note]" maxlength="1000" value="{{ $entry->note }}" @disabled($session->status->value === 'finalized')></td></tr>@endforeach</tbody></table></div>@if($session->status->value !== 'finalized' && $session->status->value !== 'cancelled' && in_array('attendance.record',$permissions,true))<button>Save register</button>@endif</form>
<div class="actions" style="margin-top:1rem">@if(in_array('attendance.finalize',$permissions,true) && in_array($session->status->value,['draft','open'],true))<form method="post" action="{{ route('attendance.finalize',$session->uuid) }}">@csrf<button>Finalize and lock</button></form>@endif @if(in_array('attendance.cancel',$permissions,true) && in_array($session->status->value,['draft','open'],true))<form method="post" action="{{ route('attendance.cancel',$session->uuid) }}">@csrf<button>Cancel session</button></form>@endif @if(in_array('attendance.reopen',$permissions,true) && $session->status->value==='finalized')<form method="post" action="{{ route('attendance.reopen',$session->uuid) }}">@csrf<input required maxlength="1000" name="reason" placeholder="Mandatory reopening reason"><button>Reopen register</button></form>@endif</div>
<script>document.getElementById('mark-all')?.addEventListener('click',()=>document.querySelectorAll('.attendance-status').forEach(x=>x.value='present'));</script>
@endsection
